@baseUrl = http://localhost:5000

@urlPath = api/v1


### Get all stations
GET {{baseUrl}}/{{urlPath}}/stations
Content-Type: application/json
Accept: application/json


### Get all journeys
GET {{baseUrl}}/{{urlPath}}/journeys?page=1&size=4
Content-Type: application/json
Accept: application/json

### Get single journeys
GET {{baseUrl}}/{{urlPath}}/journeys/64221383d5294a3e87d9988d
Content-Type: application/json
Accept: application/json
